In [7]:
import torch
import numpy as np


a = torch.arange(12).view(4, 3)
b = torch.arange(18).view(2, 3, 3)


In [22]:
arange = torch.arange(4)
idx = (arange.expand(4, -1) + arange.unsqueeze(-1) + 1) % 4
a[idx].flatten(1)

tensor([[ 3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2],
        [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
        [ 9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [3]:
obs = torch.cat([
    a.expand(4, 4, 3)[~torch.eye(4, dtype=bool)].reshape(4, -1),
    a], dim=-1)
obs

tensor([[ 3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2],
        [ 0,  1,  2,  6,  7,  8,  9, 10, 11,  3,  4,  5],
        [ 0,  1,  2,  3,  4,  5,  9, 10, 11,  6,  7,  8],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [12]:
(torch.arange(4).expand(4, -1) - torch.arange(4).view(4, 1)) % 4

tensor([[0, 1, 2, 3],
        [3, 0, 1, 2],
        [2, 3, 0, 1],
        [1, 2, 3, 0]])