In [5]:
import torch
import numpy as np


a = torch.arange(12).view(4, 3)
b = torch.arange(18).view(2, 3, 3)

(torch.rand(5) > 0.5).float()

tensor([1., 0., 1., 0., 0.])

In [22]:
arange = torch.arange(4)
idx = (arange.expand(4, -1) + arange.unsqueeze(-1) + 1) % 4
a[idx].flatten(1)

tensor([[ 3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2],
        [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
        [ 9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [3]:
obs = torch.cat([
    a.expand(4, 4, 3)[~torch.eye(4, dtype=bool)].reshape(4, -1),
    a], dim=-1)
obs

tensor([[ 3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2],
        [ 0,  1,  2,  6,  7,  8,  9, 10, 11,  3,  4,  5],
        [ 0,  1,  2,  3,  4,  5,  9, 10, 11,  6,  7,  8],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [12]:
(torch.arange(4).expand(4, -1) - torch.arange(4).view(4, 1)) % 4

tensor([[0, 1, 2, 3],
        [3, 0, 1, 2],
        [2, 3, 0, 1],
        [1, 2, 3, 0]])

In [10]:
import torch

min_xyz = torch.tensor([-1, -1, 0])
max_xyz = torch.tensor([1, 1, 1])

min_xyz.nonzero()

tensor([[0],
        [1]])

In [3]:
from dataclasses import dataclass

@dataclass
class Agent:
    a: int = 1
    b: float = 2.0
    c: str = "3"

In [19]:
from typing import Tuple
import torch

a =  torch.ones(10).unsqueeze(-1)
b = torch.arange(2)
a + b

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])